### ISSUE TITLE
Crash when setting view on TurbolinksSession

### ISSUE THREAD

**Issue by jchunch** [turbolinks/turbolinks-android#85] opened 2018-02-05 13:38 UTC
My app recently began crashing on some devices when I set the view on a TurbolinksSession. 

```
session.activity(this)
                .adapter(this)
                .view(turbolinksView) // Crashes on this line
                .visit(url);
```

It has been working fine for over a year and this recently popped up without us making any changes to our code base (I'm assuming related to a change in Chromium). Looks like Basecamp has acknowledged a similar issue on their Twitter account and was wondering if there were plans to fix the issue for this library as well. Thanks!

> 
>   at android.app.LoadedApk.forgetReceiverDispatcher (LoadedApk.java:1047)
>   at android.app.ContextImpl.unregisterReceiver (ContextImpl.java:1359)
>   at android.content.ContextWrapper.unregisterReceiver (ContextWrapper.java:651)
>   at android.content.ContextWrapper.unregisterReceiver (ContextWrapper.java:651)
>   at android.content.ContextWrapper.unregisterReceiver (ContextWrapper.java:651)
>   at org.chromium.content.browser.accessibility.LollipopWebContentsAccessibility.onDetachedFromWindow (LollipopWebContentsAccessibility.java:42)
>   at org.chromium.content.browser.ContentViewCoreImpl.onDetachedFromWindow (ContentViewCoreImpl.java:339)
>   at org.chromium.android_webview.AwContents$AwViewMethodsImpl.onDetachedFromWindow (AwContents.java:351)
>   at org.chromium.android_webview.AwContents.onDetachedFromWindow (AwContents.java:598)
>   at com.android.webview.chromium.WebViewChromium.onDetachedFromWindow (WebViewChromium.java:802)
>   at android.webkit.WebView.onDetachedFromWindowInternal (WebView.java:2365)
>   at android.view.View.dispatchDetachedFromWindow (View.java:16685)
>   at android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:3426)
>   at android.view.ViewGroup.removeViewInternal (ViewGroup.java:4956)
>   at android.view.ViewGroup.removeViewInternal (ViewGroup.java:4930)
>   at android.view.ViewGroup.removeView (ViewGroup.java:4861)
>   at com.basecamp.turbolinks.TurbolinksView.attachWebView (TurbolinksView.java:161)
>   at com.basecamp.turbolinks.TurbolinksSession.view (TurbolinksSession.java:264)

**Comment by lateplate** [comment] 2018-02-05 15:18
Hey @jchunch, thanks for calling our attention to this. We did run into this last week and patched it up with a not-so-pretty workaround. We were making sure the patch worked in the wild (it has) as well and try to find the low level root cause (we have, we think).

I'll work up a patch today and try to get it out by tomorrow. Thanks!

**Comment by lateplate** [comment] 2018-02-05 16:50
Pushed a [workaround/fix](https://github.com/turbolinks/turbolinks-android/pull/86) for now. It's been released as [version 1.0.8 of the library](https://github.com/turbolinks/turbolinks-android/releases/tag/1.0.8), so please try pointing to that version and test with Chrome 64 on Android. That should temporarily alleviate the crash.

Thanks!

**Closed by lateplate** 2018-02-05 16:50 UTC

**Comment by jchunch** [comment] 2018-02-07 17:37
@lateplate thanks for the quick fix!

**Comment by lateplate** [comment] 2018-02-07 20:10
Sure thing! Note that this is a temp workaround as we try to find a more permanent solution.
