### ISSUE TITLE
Web view background images layout issue

### ISSUE THREAD

**Issue by joemasilotti** [turbolinks/turbolinks-android#43] opened 2016-09-08 13:53 UTC
We've stumbled upon an interesting rendering issue with the library. **Adding a background cover photo to a div causes the contents to have a zero height.**

Ideally, we want a background cover image to fill the entire screen with some buttons/text along the bottom. Think of a signup/register page with a pretty background image. This was working fine for us before upgrading to 1.0.3. We didn't change any CSS or HTML markup during the upgrade.

See the following two screenshots for a demonstration of the issue. The first is the page viewed from the Android's Chrome browser, the second is the same page viewed from the Turbolinks demo app.
### Background Image in Chrome

![Background Image in Chrome](https://cloud.githubusercontent.com/assets/2092156/18351723/4fd60898-75a9-11e6-89da-4b8925209514.png)

---
### Background Image in Turbolinks Demo App

![Background Image in Turbolinks Demo App](https://cloud.githubusercontent.com/assets/2092156/18351707/4445beec-75a9-11e6-8796-e19804d6ba47.png)

---

To replicate, the changes are simple. Replace `demoapp/server/lib/turbolinks_demo/views/index.erb` with the following:

``` html
<style>
.bg {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  background: url('https://help.basecamp.com/images/logo-bc.png') no-repeat top left;
  background-size: cover;
}
.content {
  position: absolute;
  right: 16px;
  left: 16px;
  bottom: 0;
}
</style>

<div class="bg">
  <div class="content">
    <p><strong>Hello from Turbolinks!</strong> This demo app will help you get acquainted with the framework.</p>

    <ul>
      <li><a href="/one">Open a new activity</a> by following a regular link.</li>
      <li><a href="/slow">See the loading indicator</a> and test Turbolinks’ preview cache with this slow-loading page.</li>
      <li><a href="/nonexistent">Trigger an HTTP 404</a> to see how Turbolinks handles error responses.</li>
    </ul>
  </div>
</div>
```

---

Is this an issue with the framework or is Android doing something funky with our CSS? Of note, commenting out all of the pull-to-refresh code fixes the display issue.

**Comment by lateplate** [comment] 2016-09-30 16:41
Confirmed. I snapshot back to 1.0.2, and see the same results. 1.0.3 doesn't show the background image, 1.0.2 is OK.

This certainly could be related to nesting the WebView inside a SwipeRefreshLayout. It's part of the support lib which was new for 1.0.3, and though I don't have details yet, it wouldn't surprise me if a support lib component affected rendering of webview.

@joemasilotti Were you able to test commenting out specifically just the SwipeRefreshLayout stuff, or did you snapshot back all the way to 1.0.2? Just curious because 1.0.3 also had a number of other changes. Were you able to find any workaround for now?

**Comment by joemasilotti** [comment] 2016-10-21 16:16
Whoa, sorry for the late reply - didn't see this until now.

Commenting out `SwipeRefreshLayout`, and only that, fixed the issue entirely.

**Comment by frankrrr** [comment] 2016-11-10 13:24
We have the same problem. Seems that it has something to do with the document.height. See the `.header-home` container on https://www.ticketswap.com. It has a `min-height` of `100%`, but looks like this:

![cw52qucwiaaim1g](https://cloud.githubusercontent.com/assets/345811/20178379/293fd018-a751-11e6-9ef1-0d7a342f51d0.jpg)

@joemasilotti Did you find a solution?

1.0.2 works, 1.0.3/4 contain this bug.

**Comment by joemasilotti** [comment] 2016-11-10 16:38
@frankrrr The only reliable solution we found is to remove pull-to-refresh. This forces us to fork and maintain our own copy of the repo, which is less than idea.

**Comment by risinglf** [comment] 2016-12-15 09:57
Hi @lateplate!

Thanks for this great project. Any news about merging the @kassim 's PR?

**Comment by joemasilotti** [comment] 2016-12-15 11:03
Earlier this week I confirmed that #60 fixes the issue for us. 👍

**Comment by lateplate** [comment] 2016-12-15 15:37
@risinglf @joemasilotti @kassim Thanks. Dropped some minor feedback in the PR. Once I can do a quick smoke test and those changes are made, we should be good to merge.

**Comment by lateplate** [comment] 2017-01-27 17:27
Merged [the fix](https://github.com/turbolinks/turbolinks-android/pull/63#event-939621161).

**Closed by lateplate** 2017-01-27 17:27 UTC
Labels: bug
