### ISSUE TITLE
Links with disabled Turbolinks are still being processed by library

### ISSUE THREAD

**Issue by DarkMinstrel** [turbolinks/turbolinks-android#64] opened 2016-12-23 15:43 UTC
In html I have a link annotated with `data-turbolinks="false"`, but clicking this link in Android app triggers method `visitLocationWithAction` to be called with action `advance`. Also, it is not clear, how should I catch such links, since `TurbolinksAdapter` does not have any dedicated callback.

**Comment by lateplate** [comment] 2017-01-27 17:31
I'm not sure how that would be possible, but I'd be happy to look at some provided code.

You may want to double check your Rails code to ensure a Turbolinks visit isn't firing. If a standard `<a href="">` is being fired, nothing would tell the Turbolinks Javascript to fire, and the webview would do a normal `loadUrl()`.

This would put Turbolinks Android in an unexpected state, so you'd want to handle it another way. But it still shouldn't fire a TL visit from the Rails side. 

Closing for now, but will re-open if you have more comments/code to share.

**Comment by michiels** [comment] 2017-03-24 19:30
Hi @lateplate I'm hitting this bug on a Turbolinks Android 1.0.6 app. You can find the live code for this on http://stemapp.appsfordemocracy.nl/vote_events/index?year=2017 on the buttons "Bekijk deze motie", which have a `data-turbolinks="false"` attribute.

The Android side is pretty much a blank slate implementation of a `TurbolinksAdapter` interface (see below). I've added a debug call to prove that the `visitProposedToLocationWithAction` callback is called when clicking the button with the `data-turbolinks="false"` attribute. 

```
package com.michielsikkes.utrecht.stemapp;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;

import com.basecamp.turbolinks.TurbolinksAdapter;
import com.basecamp.turbolinks.TurbolinksSession;
import com.basecamp.turbolinks.TurbolinksView;

public class MainActivity extends AppCompatActivity implements TurbolinksAdapter {
    private static final String BASE_URL = "http://stemapp.appsfordemocracy.nl";
    private static final String INTENT_URL = "intentUrl";

    private String location;
    private TurbolinksView turbolinksView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        turbolinksView = (TurbolinksView) findViewById(R.id.turbolinks_view);
        TurbolinksSession.getDefault(this).setDebugLoggingEnabled(true);

        location = getIntent().getStringExtra(INTENT_URL) != null ? getIntent().getStringExtra(INTENT_URL) : BASE_URL;

        TurbolinksSession.getDefault(this)
                .activity(this)
                .adapter(this)
                .view(turbolinksView)
                .visit(location);
    }

    @Override
    public void onPageFinished() {

    }

    @Override
    public void onReceivedError(int errorCode) {

    }

    @Override
    public void pageInvalidated() {

    }

    @Override
    public void requestFailedWithStatusCode(int statusCode) {

    }

    @Override
    public void visitCompleted() {

    }

    @Override
    public void visitProposedToLocationWithAction(String location, String action) {
        Log.d("STEMAPP_DEBUG", "visit not external");
        Intent intent = new Intent(this, MainActivity.class);
        intent.putExtra(INTENT_URL, location);
        this.startActivity(intent);
    }

    @Override
    protected void onRestart() {
        super.onRestart();

        // Since the webView is shared between activities, we need to tell Turbolinks
        // to load the location from the previous activity upon restarting
        TurbolinksSession.getDefault(this)
                .activity(this)
                .adapter(this)
                .restoreWithCachedSnapshot(true)
                .view(turbolinksView)
                .visit(location);
    }
}
```

**Comment by michiels** [comment] 2017-03-24 21:09
Some more info: I can actually verify that my "turbolinks:before-visit" is not triggered when clicking an external link or a link with `data-turbolinks="false"`. However, the link still seems to trigger a call to `visitProposedToLocationWithAction` so it fails to load an actual external browser, but still tries to execute the URL as new activity in the app.

**Comment by michiels** [comment] 2017-03-24 21:18
For now, the only workaround to open an external URL for me is having this function. But that doesn't really solve the `data-turbolinks="false"` attribute problem yet.

```
    @Override
    public void visitProposedToLocationWithAction(String location, String action) {
        if(!location.contains(BASE_URL)) {
            Intent i = new Intent(Intent.ACTION_VIEW);
            i.setData(Uri.parse(location));
            startActivity(i);
        } else {
            Intent intent = new Intent(this, MainActivity.class);
            intent.putExtra(INTENT_URL, location);
            this.startActivity(intent);
        }
    }
```

**Comment by orischwartz** [comment] 2017-09-12 13:00
We have fairly vanilla Android and iOS turbolinks apps and we're seeing this same behavior. 

`turbolinks-android` triggers callbacks to `visitProposedToLocationWithAction` on `<a>` clicks that have the `data-turbolinks="false"` attribute set. (The iOS app correctly opens these in an external browser without calling `didProposeVisitToURL`).

Can this issue be re-opened? I will provide more debugging info shortly. Thank you.

**Comment by orischwartz** [comment] 2017-09-12 14:17
Here is a small reproducible test case using the demoapp as a starting point. I could be misusing the library but this same scenario is handled by turbolinks-ios.

### Steps to Reproduce
1. Configure a local or test server to return the `index.html` contents below (in this example `10.7.2.74:8081` is used).
1. Apply the diff below to the demoapp's `MainActivity.java` for debugging purposes:
1. Run the app and click on the first link, then click on the second link
 and search the logs for `issue#64`. 

### Expected Behavior
Clicking the second link should open an external browser because it has the `data-turbolinks="false"` attribute

### Actual Behavior
Turbolinks Android library attempts to handle both clicks. Here is the log output from attempting to visit google.com (second link):

```
D/TurbolinksLog: Overriding load: https://www.google.com/
I/issue#64: visitProposedToLocationWithAction() called with https://www.google.com/
D/TurbolinksLog: Visiting current stored location: https://www.google.com/
I/chromium: [INFO:CONSOLE(5)] "Uncaught SecurityError: Failed to execute 'pushState' on 'History': A history state object with URL 'https://www.google.com/' cannot be created in a document with origin 'http://10.7.2.74:8081' and URL 'http://10.7.2.74:8081/index.html'.", source: https://cdnjs.cloudflare.com/ajax/libs/turbolinks/5.0.3/turbolinks.js (5)
I/chromium: [INFO:CONSOLE(0)] "XMLHttpRequest cannot load https://www.google.com/. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://10.7.2.74:8081' is therefore not allowed access. The response had HTTP status code 405.", source: http://10.7.2.74:8081/index.html (0)
```

### Minimal `index.html` to be served locally
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Links with disabled Turbolinks are still being processed by library #64</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <h1>Links with disabled Turbolinks are still being processed by library #64</h1>

    <p>Here is a <a href="/index.html">link</a> that <em>should</em> be handled by turbolinks</p>

    <p>Here is a <a href="https://www.google.com" data-turbolinks="false">link</a> that <em>should not</em> be handled by turbolinks</p>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/turbolinks/5.0.3/turbolinks.js"></script>
  </body>
</html>
```

### `MainActivity.java` diff
```diff
+++ b/demoapp/src/main/java/com/basecamp/turbolinks/demo/MainActivity.java
@@ -3,6 +3,7 @@ package com.basecamp.turbolinks.demo;
 import android.content.Intent;
 import android.os.Bundle;
 import android.support.v7.app.AppCompatActivity;
+import android.util.Log;

 import com.basecamp.turbolinks.TurbolinksSession;
 import com.basecamp.turbolinks.TurbolinksAdapter;
@@ -10,7 +11,7 @@ import com.basecamp.turbolinks.TurbolinksView;

 public class MainActivity extends AppCompatActivity implements TurbolinksAdapter {
     // Change the BASE_URL to an address that your VM or device can hit.
-    private static final String BASE_URL = "http://10.0.1.100:9292";
+    private static final String BASE_URL = "http://10.7.2.74:8081";
     private static final String INTENT_URL = "intentUrl";

     private String location;
@@ -91,6 +92,7 @@ public class MainActivity extends AppCompatActivity implements TurbolinksAdapter
     // routing logic to take you to the right place within your app.
     @Override
     public void visitProposedToLocationWithAction(String location, String action) {
+        Log.i("issue#64", "visitProposedToLocationWithAction() called with " + location);
         Intent intent = new Intent(this, MainActivity.class);
         intent.putExtra(INTENT_URL, location);
```

**Comment by lazaronixon** [comment] 2018-01-15 22:57
Please re-open this issue...

**Closed** 2020-12-22 17:34 UTC
