### ISSUE TITLE
App crashes with OOM error

### ISSUE THREAD

**Issue by leequarella** [turbolinks/turbolinks-android#67] opened 2017-02-10 15:41 UTC
Using an app based on the demo app (copy/pasted MainActivity.java, activity_main.xml, etc) and running it against the demo sinatra server, each time a link is clicked the app memory usage climbs about 6mb and stays there.  After navigating enough times, android gives the user an error saying `Unfortunately, <yourapp> has stopped`.

And this is found in the app logs:

```
java.lang.OutOfMemoryError: Failed to allocate a 14261772 byte allocation with 4353808 free bytes and 4MB until OOM
at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
at android.graphics.Bitmap.nativeCreate(Native Method)
at android.graphics.Bitmap.createBitmap(Bitmap.java:975)
at android.graphics.Bitmap.createBitmap(Bitmap.java:946)
at android.graphics.Bitmap.createBitmap(Bitmap.java:913)
at com.basecamp.turbolinks.TurbolinksView.getScreenshotBitmap(TurbolinksView.java:230)
at com.basecamp.turbolinks.TurbolinksView.screenshotView(TurbolinksView.java:209)
at com.basecamp.turbolinks.TurbolinksView.attachWebView(TurbolinksView.java:160)
at com.basecamp.turbolinks.TurbolinksSession.view(TurbolinksSession.java:264)
at com.thoughtmesa.agrimanage.MainActivity.onCreate(MainActivity.java:46)
at android.app.Activity.performCreate(Activity.java:6876)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
at android.app.ActivityThread.access$1100(ActivityThread.java:222)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:7237)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

Here is the snapshot of use. Each step up in memory allocation is a click of the link from the demo app "Go to page one" or "Go to page two":
<img width="1403" alt="screen shot 2017-02-10 at 10 39 41 am" src="https://cloud.githubusercontent.com/assets/879547/22832759/4c4998d6-ef7d-11e6-8fc2-759cb9e5e525.png">

**Comment by KeithP** [comment] 2017-02-10 16:22
@leequarella We had the same issue last year and did the following hack to solve it - but lost the illusion of fast page loads :(  
We changed both of these from xxxx(true) to xxx(false) in MainActivity.java:

1.  .restoreWithCachedSnapshot(true) 
2. TurbolinksSession.getDefault(this).setScreenshotsEnabled(true); 

Would like to know what is the solution though, it seems fairly fundamental to using this.

**Comment by leequarella** [comment] 2017-02-13 20:18
Using @KeithP's method, I found that the memory increase was reduced significantly. From 6mb per click to about 0.2mb per click.  However, the problem still seems to exist and after enough use we'll hit the same error.

Before @KeithP:

```    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        // Find the custom TurbolinksView object in your layout
        turbolinksView = (TurbolinksView) findViewById(R.id.turbolinks_view);

        // For this example we set a default location, unless one is passed in through an intent
        location = getIntent().getStringExtra(INTENT_URL) != null ? getIntent().getStringExtra(INTENT_URL) : BASE_URL;

        // Execute the visit
        TurbolinksSession.getDefault(this)
                .activity(this)
                .adapter(this)
                .view(turbolinksView)
                .visit(location);
    }
```

After

```
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        // Find the custom TurbolinksView object in your layout
        turbolinksView = (TurbolinksView) findViewById(R.id.turbolinks_view);

        // For this example we set a default location, unless one is passed in through an intent
        location = getIntent().getStringExtra(INTENT_URL) != null ? getIntent().getStringExtra(INTENT_URL) : BASE_URL;

       TurbolinksSession.getDefault(this).setScreenshotsEnabled(false);
        // Execute the visit
        TurbolinksSession.getDefault(this)
                .activity(this)
                .adapter(this)
                .view(turbolinksView)
                .restoreWithCachedSnapshot(false)
                .visit(location);
    }
```

**Comment by dodecaphonic** [comment] 2017-02-14 14:18
The thing with the sample app is that it relies on stacking Activities to provide navigation. This doesn't scale well if your navigation gets deep, since Android will keep all previous Activities in memory (that is, you're not merely replacing the WebView you have, but creating a new Activity with a new layout and its own contents).

I don't know what's the official/recommended way to do it, but you can go in a couple of directions:

- Keep your own navigation stack using a single Activity, pushing and popping URLs with `visitProposedToLocationWithAction`, and popping them with `onBackPressed` (calling `TurbolinksSession.visit`)
   - This is the most straightforward thing to do
   - You'll lose the default ProgressView behavior (i.e. when you navigate forward and the WebView is already loaded, it won't show it), but it's easily remedied
   - It will be more of a hassle to define different Android layouts
- Map whatever screens you have (and their relationships) and Route between them by implementing TurbolinksAdapter as a separate routing class. Maybe by codifying how things flow, you can reuse things. This will require more Android-fu, and is probably not what you want when you adopt turbolinks

I've personally done the first one, and it's not a lot of code. Memory usage for my app is steady at 16MB.

**Comment by lateplate** [comment] 2017-05-22 20:35
Hi everyone, sorry for the delay in responding. Here's an update...

### Cause
The memory spikes are caused by the built-in screenshotting feature, which when restoring from cache, defaults to true. 

Whenever we visit a new page, we take a bitmap screenshot of the last as a UI trick to improve perceived speed (the screenshot is shown for a split second before being replaced with the actual webview).

### Workaround 1: Use 1.0.7
In version `1.0.7` we published [a workaround fix](https://github.com/turbolinks/turbolinks-android/pull/71) that first checks the available heap before taking the screenshot. If you don't have more than 10% available left on the heap, we bypass taking the screenshot.

This isn't perfect by any stretch. The % value we selected is arbitrary (but should work OK). It also means that if your device is low on heap, you won't get a screenshot going back in some cases, which could be a curious/unexpected UI interaction (you'd still get the progress spinner).

The better fix will be to write that screenshot to disk instead of keeping it in memory. We'll pay a hit for the disk IO, but it'll certainly remove any possibility of OOMs. It's just a matter of us (or someone) carving out a little time to doing that work. 

### Workaround 2: Disable screenshots
Another workaround is to [disable screenshots altogether](https://github.com/turbolinks/turbolinks-android#bitmap-screenshots) (as others have mentioned as well). While the heap check in workaround 1 should work in most cases, a guaranteed way to keep the heap small will be to disable it entirely.

Hope that helps. Thanks!

**Comment by lateplate** [comment] 2017-05-22 20:37
Going to close this in favor of #73.

**Closed by lateplate** 2017-05-22 20:37 UTC
